In [26]:
#IMPORTING LIBRARIES
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
#LOADING AND PROCESSING DATA
df=pd.read_csv('/content/Women Clothing E-Commerce Review.csv')
df.head()
df.info()
df.shape
df.isna().sum()
df[df['Review']==""]=np.nan
df['Review'].fillna("No Review",inplace=True)
df.isna().sum()
df['Review']
df.columns
#PREPARING DATA FOR MODELING
X=df['Review']
y=df['Rating']
df['Rating'].value_counts()
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7,stratify=y,random_state=2529)
X_train.shape,X_test.shape,y_train.shape,y_test.shape
#FEATURE EXTRACTION
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(stop_words='english')
X_train=cv.fit_transform(X_train)
X_test=cv.transform(X_test)
cv.get_feature_names_out()
X_train.toarray()
cv.get_feature_names_out()
X_train.toarray()
#MODEL TRAINING AND PREDICTION
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(X_train, y_train)
y_pred=model.predict(X_test)
y_pred.shape
y_pred
model.predict_proba(X_test)
#MODEL EVALUATION
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(classification_report(y_test,y_pred))
#Re-labeling and Re-training (Binary Classification)
df['Rating'].value_counts()
df.replace({'Rating':{1:0,2:0,3:0,4:1,5:1}},inplace=True)
y=df['Rating']
x=df['Review']
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,stratify=y,random_state=2529)
x_train.shape,x_test.shape,y_train.shape,y_test.shape
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(lowercase=True,analyzer='word',stop_words='english',max_features=5000)
x_train = cv.fit_transform(x_train)
x_test=cv.transform(x_test)
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
y_pred.shape
y_pred
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Clothing ID        23486 non-null  int64 
 1   Age                23486 non-null  int64 
 2   Title              19676 non-null  object
 3   Review             22641 non-null  object
 4   Rating             23486 non-null  int64 
 5   Recommended        23486 non-null  int64 
 6   Positive Feedback  23486 non-null  int64 
 7   Division           23472 non-null  object
 8   Department         23472 non-null  object
 9   Category           23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.8+ MB


<ipython-input-26-ac7c9ad54c05>:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Review'].fillna("No Review",inplace=True)


[[  17   45  116   26   49]
 [   6   27  235  105   97]
 [   3   25  332  269  232]
 [   1    7  133  472  910]
 [   1    4   58  305 3571]]
              precision    recall  f1-score   support

           1       0.61      0.07      0.12       253
           2       0.25      0.06      0.09       470
           3       0.38      0.39      0.38       861
           4       0.40      0.31      0.35      1523
           5       0.73      0.91      0.81      3939

    accuracy                           0.63      7046
   macro avg       0.47      0.35      0.35      7046
weighted avg       0.58      0.63      0.59      7046

              precision    recall  f1-score   support

           1       0.61      0.07      0.12       253
           2       0.25      0.06      0.09       470
           3       0.38      0.39      0.38       861
           4       0.40      0.31      0.35      1523
           5       0.73      0.91      0.81      3939

    accuracy                           0.63 